name: huffman_table
description: Implements Huffman coding for data compression, providing methods to encode and decode data using frequency-based tree structures.
version: 1.0.0
repository: https://github.com/TimeLord2010/huffman_table

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
